In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
flats=pd.read_csv("flats_missing_val.csv")
houses=pd.read_csv("house_missing_val.csv")

In [7]:
flats.columns

Index(['society', 'bedrooms', 'baths', 'link', 'floors_in_building', 'price',
       'area', 'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'other_rooms', 'luxury_score',
       'furnishing_score', 'floor', 'agePossession'],
      dtype='object')

In [8]:
houses.columns

Index(['society', 'bedrooms', 'baths', 'rooms', 'link', 'floors', 'price',
       'area', 'area_sqft', 'kitchens', 'store_rooms', 'price_per_sqft',
       'drawing_room', 'dining_room', 'lounge_or_sitting_room', 'laundry_room',
       'study_room', 'prayer_room', 'powder_room', 'gym', 'steam_room',
       'servant_quarters_flag', 'store_rooms_flag', 'kitchens_flag',
       'other_rooms', 'luxury_score', 'furnishing_score', 'agePossession',
       'has_servant_room'],
      dtype='object')

In [9]:
drop_cols_flats = [
    'link',
    'area',                # already have area_sqft
    'price_per_sqft',      # leakage ❌
    'society',             # you decided not to use
]

flats.drop(columns=drop_cols_flats, inplace=True)

In [10]:
drop_cols_houses = [
    'link',
    'area',
    'price_per_sqft',      # leakage ❌
    'society',
    'rooms',               # already extracted
    'servant_quarters_flag',
    'store_rooms_flag',
    'kitchens_flag',
]

houses.drop(columns=drop_cols_houses, inplace=True)

In [11]:
flats.rename(columns={'floor': 'floors'}, inplace=True)

In [12]:
flats.drop(columns=['floors_in_building'], inplace=True)

In [13]:
flats['property_type'] = 0   # flat
houses['property_type'] = 1  # house

In [14]:
flats.columns

Index(['bedrooms', 'baths', 'price', 'area_sqft', 'servant_quarters',
       'kitchens', 'store_rooms', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'other_rooms', 'luxury_score',
       'furnishing_score', 'floors', 'agePossession', 'property_type'],
      dtype='object')

In [15]:
houses.columns

Index(['bedrooms', 'baths', 'floors', 'price', 'area_sqft', 'kitchens',
       'store_rooms', 'drawing_room', 'dining_room', 'lounge_or_sitting_room',
       'laundry_room', 'study_room', 'prayer_room', 'powder_room', 'gym',
       'steam_room', 'other_rooms', 'luxury_score', 'furnishing_score',
       'agePossession', 'has_servant_room', 'property_type'],
      dtype='object')

In [16]:
flats['has_servant_room'] = (flats['servant_quarters'] > 0).astype(int)
flats.drop(columns=['servant_quarters'], inplace=True)

In [17]:
set(flats.columns) == set(houses.columns)

True

In [18]:
df = pd.concat([flats, houses], ignore_index=True)

In [19]:
df.head()

,bedrooms,baths,price,area_sqft,kitchens,store_rooms,drawing_room,dining_room,lounge_or_sitting_room,laundry_room,...,powder_room,gym,steam_room,other_rooms,luxury_score,furnishing_score,floors,agePossession,property_type,has_servant_room
0,4.0,4.0,4.55,3264.0,1.0,1.0,1,1,1,1,...,1,0,0,0,135.0,37,3.0,New Property,0,1
1,4.0,5.0,4.50,3318.4,1.0,0.0,1,1,0,0,...,0,0,0,1,150.0,31,3.0,New Property,0,1
2,3.0,4.0,3.55,2720.0,1.0,1.0,1,1,1,1,...,1,1,1,1,156.0,49,3.0,New Property,0,1
3,4.0,4.0,4.45,2067.2,2.0,1.0,1,1,0,0,...,0,0,0,1,125.0,18,3.0,New Property,0,1
4,4.0,5.0,4.65,3318.4,1.0,1.0,1,1,0,0,...,0,0,0,1,100.0,18,3.0,New Property,0,1

In [20]:
df.shape

(23081, 22)

In [21]:
drop_cols = [
    'powder_room',
    'steam_room',
    'study_room',
    'lounge_or_sitting_room',
    'laundry_room',
    'prayer_room',
    'drawing_room',
    'dining_room',
    'other_rooms'
]

df=df.drop(columns=drop_cols)

In [22]:
df.shape

(23081, 13)

In [ ]:
df.to_csv("houses_flats.csv",index=False)

In [24]:
df.sample(20)

,bedrooms,baths,price,area_sqft,kitchens,store_rooms,gym,luxury_score,furnishing_score,floors,agePossession,property_type,has_servant_room
1069,2.0,2.0,1.4800,952.0000,1.0,1.0,0,111.0,33,5.0,New Property,0,0
11891,4.0,5.0,2.1000,1442.9303,2.0,1.0,1,64.0,15,3.0,New Property,1,1
13190,5.0,6.0,3.4500,1361.2550,2.0,1.0,1,66.0,25,2.0,Undefined,1,0
21973,3.0,3.0,1.3000,816.7530,2.0,1.0,0,23.0,0,2.0,Undefined,1,0
3560,3.0,4.0,2.8000,1361.2550,1.0,1.0,0,32.0,13,2.0,Undefined,1,0
10900,5.0,5.0,3.4000,2722.5100,2.0,1.0,0,38.0,11,2.0,Undefined,1,0
15947,5.0,7.0,10.2500,5989.5220,2.0,1.0,0,40.0,6,2.0,New Property,1,0
7359,6.0,7.0,13.0000,5989.5220,3.0,1.0,1,62.0,25,2.0,New Property,1,1
12318,6.0,7.0,11.9900,5445.0200,2.0,1.0,1,31.0,24,2.0,Undefined,1,0
1865,1.0,1.0,0.7751,136.0000,1.0,0.0,1,186.0,49,7.0,New Property,0,0
2236,1.0,2.0,3.1000,1496.0000,2.0,1.0,1,186.0,49,2.0,Relatively New,0,1
17792,4.0,4.0,2.1000,1361.2550,2.0,1.0,0,41.0,8,2.0,Undefined,1,1
18203,3.0,3.0,1.4000,816.7530,2.0,1.0,1,64.0,14,2.0,New Property,1,0
10688,7.0,7.0,7.0000,3267.0120,2.0,1.0,1,66.0,25,2.0,New Property,1,1
16636,3.0,3.0,2.6500,1361.2550,2.0,1.0,0,58.0,25,2.0,Relatively New,1,0
11000,4.0,4.0,1.7000,1361.2550,2.0,1.0,0,49.0,12,2.0,New Property,1,0
8929,5.0,5.0,7.1000,5445.0200,1.0,1.0,1,50.0,14,2.0,New Property,1,0
14432,4.0,5.0,1.1500,1089.0040,1.0,1.0,1,66.0,25,2.0,Old Property,1,1
14091,3.0,5.0,2.2000,1361.2550,2.0,1.0,0,10.0,5,2.0,Undefined,1,0
8698,4.0,5.0,3.7500,1633.5060,2.0,1.0,0,66.0,15,3.0,Moderately Old,1,1

In [25]:
import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    KFold,
    GridSearchCV
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (
    StandardScaler,
    OrdinalEncoder
)

from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    r2_score,
    mean_absolute_error
)

from xgboost import XGBRegressor

In [26]:
# Numerical columns
num_cols = [
    'bedrooms',
    'baths',
    'area_sqft',
    'kitchens',
    'store_rooms',
    'gym',
    'luxury_score',
    'furnishing_score',
    'floors'
]

# Ordinal columns
ordinal_cols = [
    'agePossession'
]

# Binary columns
binary_cols = [
    'property_type',
    'has_servant_room'
]

In [27]:
preprocessor = ColumnTransformer(
    transformers=[

        ('num',
         StandardScaler(),
         num_cols),

        ('ord',
         OrdinalEncoder(),
         ordinal_cols),

        ('bin',
         'passthrough',
         binary_cols)

    ],
    remainder='drop'
)

In [28]:
X = df[
    num_cols +
    ordinal_cols +
    binary_cols
]

y = df['price']

In [29]:
y_transformed = np.log1p(y)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.2,
    random_state=42
)

In [31]:
pipeline = Pipeline([

    ('preprocessor', preprocessor),

    ('regressor',
     XGBRegressor(
         objective='reg:squarederror',
         random_state=42
     ))
])

In [32]:
param_grid = {

    'regressor__n_estimators': [200, 300],

    'regressor__max_depth': [4, 6],

    'regressor__learning_rate': [0.05, 0.1],

    'regressor__subsample': [0.8, 1.0],

    'regressor__colsample_bytree': [0.8, 1.0]
}

In [33]:
kfold = KFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

In [34]:
search = GridSearchCV(

    pipeline,

    param_grid,

    cv=kfold,

    scoring='r2',

    n_jobs=-1,

    verbose=4
)

In [35]:
search.fit(X_train, y_train)

Fitting 10 folds for each of 32 candidates, totalling 320 fits

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedrooms',
                                                                          'baths',
                                                                          'area_sqft',
                                                                          'kitchens',
                                                                          'store_rooms',
                                                                          'gym',
                                                                          'luxury_score',
                                                                          'furnishing_score',
                                                                          'floors']),
                                                                        ('ord',
                                                                         OrdinalEncoder(),
                                                                         ['agePossession']),
                                                                        ('bin',
                                                                         'passthrough',
                                                                         ['property_type'...
                                                     min_child_weight=None,
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=None,
                                                     num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'regressor__colsample_bytree': [0.8, 1.0],
                         'regressor__learning_rate': [0.05, 0.1],
                         'regressor__max_depth': [4, 6],
                         'regressor__n_estimators': [200, 300],
                         'regressor__subsample': [0.8, 1.0]},
             scoring='r2', verbose=4)

In [36]:
search.best_score_

np.float64(0.8979108567898061)

In [37]:
search.best_score_

np.float64(0.8979108567898061)

In [39]:
final_pipe = search.best_estimator_

In [40]:
y_pred_log = final_pipe.predict(X_test)

In [41]:
y_pred = np.expm1(y_pred_log)

y_actual = np.expm1(y_test)

In [42]:
mean_absolute_error(
    y_actual,
    y_pred
)

1.2820506463303978

In [43]:
r2_score(
    y_actual,
    y_pred
)

0.7970109428913217